[package]
name = "syntaxfmt-macros"
version = "0.2.1"
edition = "2021"
rust-version = "1.70"
license = "MIT OR Apache-2.0"
description = "Procedural macros for the syntaxfmt crate."
homepage = "https://github.com/jngls/syntaxfmt"
repository = "https://github.com/jngls/syntaxfmt"
documentation = "https://docs.rs/syntaxfmt"
readme = "README.md"
categories = ["development-tools::procedural-macro-helpers"]
keywords = ["syntax", "formatting", "derive", "macro"]

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
syntaxfmt = { path = "../.." }

[features]

# [lints]
# workspace = true
