[package]
name = "syntaxfmt-macros"
version = "0.1.0"
edition = "2024"

[lib]
proc-macro = true

[dependencies]
syn = { version = "2", features = ["full", "extra-traits"] }
quote = "1"
proc-macro2 = "1"

[dev-dependencies]
syntaxfmt = { path = "../.." }

# [lints]
# workspace = true
